features: {}

end_to_end_tests:
  group_name: End to end tests

form_ids:
  smoke_test:
  s3:

forms_admin:
  auth:
    username:
    password:
  url:

forms_product_page:
  url:

forms_runner:
  url:

aws:
  s3_submission_bucket_name:
  s3_submission_iam_role_arn:
  email_receiver_s3_bucket_name:

govuk_notify:
  api_key:

govuk_one_login:
  user_email:
  user_password:
  user_otp_secret_key:

submission_status_api:
  secret:

confirmation_email:
