form_ids:
  smoke_test: 2570
  s3: 5086

forms_admin:
  url: https://admin.forms.service.gov.uk

forms_product_page:
  url: https://www.forms.service.gov.uk

forms_runner_url:
  url: https://submit.forms.service.gov.uk

aws:
  s3_submission_bucket_name: govuk-forms-submissions-to-s3-test
  s3_submission_iam_role_arn: arn:aws:iam::443944947292:role/govuk-s3-end-to-end-test-production
  email_receiver_s3_bucket_name: govuk-forms-production-test-emails

confirmation_email: confirmation-email-tests@forms.service.gov.uk
