features: {}

form_ids:
  smoke_test: 1
  s3: 2

forms_admin:
  url: http://localhost:3000

forms_runner:
  url: http://localhost:3001

forms_product_page:
  url: http://localhost:3002

submission_status_api:
  secret: test_token

aws:
  file_upload_s3_bucket_name: govuk-forms-submissions-to-s3-test
  s3_submission_iam_role_arn: arn:aws:iam::498160065950:role/govuk-s3-end-to-end-test-dev
  email_receiver_s3_bucket_name: govuk-forms-dev-test-emails

govuk_one_login:
  user_email: copy-of-answers-emails-tests@dev.forms.service.gov.uk
